version: '3'
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${DOCKER_DB_PORT}:5432"

  cache:
    image: redis:6.2-alpine
    restart: always
    volumes: 
      - cache:/var/lib/redis/data
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
  auth:
    build:
      context: ./src
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: "make start"

volumes:
  db:
  cache: