version: '3'

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '{&REDIS_PORT}:6379'
    volumes: 
      - cache:/var/lib/redis/data

  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    depends_on:
      - cashe

  etl:
    build:
      context: ./ETL
    env_file:
      - ./ETL/.env
    command: "make start"
    depends_on:
      - db    

  admin:
    build:
      context: ./DjangoAdmin/src
    restart: always
    env_file:
      - .env
    ports:
      -"8001:8000"
    command: "make start"
    depends_on:
      - etl

volumes:
  db: