version: '3'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes: 
      - cache:/var/lib/redis/data
  db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    volumes:
      - elastic:/usr/share/elasticsearch/data
    env_file:
      - .env
    ports:
      - "9200:9200"
  etl:
    build: 
      context: ./etl
    env_file:
      - .env
    depends_on:
      - elastic
    entrypoint: >
      sh -c "sleep 15
      && python main.py"
  search_service:
    build: 
      context: ./src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - etl
    entrypoint: >
      sh -c "sleep 17
      && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"    
    
volumes:
  db:
  elastic:
  cache: